apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "noticias.labels" . | nindent 4 }}
type: Opaque
data:
  noticias_mongo_url: {{ .Values.noticiasMongoUrl | b64enc }}