name: Despliegue en Okteto

on:
  push:
    branches: [ master ]

jobs:
  #test:
   # uses: MUISCDGTI/noticias-backend/.github/workflows/tests.yml@master
  deploy:
    #needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{secrets.OKTETO_TOKEN}}
          
      - name: Okteto Pipeline
        uses: okteto/pipeline@latest
        with:
          name: noticias-backend
          namespace: fis-josenggn
